### PR TITLE
reintroduce setup from inputstream

### PR DESCRIPTION
**Pull request by marekpalenik**

### CODE REVIEW

**Comment by ktor** [comment]
Hi @marekpalenik, why do you need that?

**Comment by marekpalenik** [comment]
@ktor : 1. customers' project setup uses inputstreams 
2. my private testing/learning project uses inputstreams

**Comment by ktor** [comment]
@marekpalenik, thx, until this is resolved- version 2.1.4 still has InputStreams if you need to be fast with the upgrade. You can download it here: https://github.com/ableneo/liferay-db-setup-core/releases/tag/2.1.4

What you've written just states that you use the method, I understand that. Why do you need it? Could you use anything else than an InputStream?

2.2.x is incompatible with 2.1.x also for that reason and I hesitate to support InputStream in public api for following reason: when an InputStream is managed outside of the library and not properly managed (closed) it can easily create leaks (steal limited system resources). I feel this is critical as we use the library in production setups. To reduce the risk I've chosen to open and close streams inside within the library to stay safe.

Would String method argument be OK in your setup?

**Comment by ktor** [comment]
Hi Marek, 

I was thinking about it and discussing with colleagues. My arguments against InputStream seems weaker and weaker to me. Let's make a following deal. 

LiferaySetup will only accept Setup object as an argument to work with and MarshallUtil will parse xml from whatever source, including InputStream. 

We'll separate responsibility for unmarshalling away from setup operations. 

What do you think?

**Pull request merged**
